In [14]:
import pandas as pd

In [20]:
impressions_path= "impressions.json"
impressions= pd.read_json(impressions_path)
impressions.head()

   app_id  advertiser_id country_code                                    id
0      32            8.0           UK  a39747e8-9c58-41db-8f9f-27963bc248b5
1      30           17.0         None  5deacf2d-833a-4549-a398-20a0abeec0bc
2       4           15.0           IT  2ae9fd3f-4c70-4d9f-9fe0-98cb2f0b7521
3      22           20.0           IT  fbb52038-4db1-46d3-a4de-108fd12cbfc7
4       9           32.0               b15449b6-14c9-406b-bce9-749805dd6a3e

In [21]:
clicks_path= "clicks.json"
clicks= pd.read_json(clicks_path)
clicks.head()

                          impression_id   revenue
0  97dd2a0f-6d42-4c63-8cd6-5270c19f20d6  2.091226
1  43bd7feb-3fea-40b4-a140-d01a35ec1f73  2.479458
2  1b04c706-e3d7-4f70-aac8-25635fa24250  1.061739
3  31214d91-d950-4464-8316-ed3d302d49d3  2.074762
4  fbb52038-4db1-46d3-a4de-108fd12cbfc7  2.783758

In [22]:
clicks = clicks.rename(columns={"impression_id": "id"})
clicks.head()

                                     id   revenue
0  97dd2a0f-6d42-4c63-8cd6-5270c19f20d6  2.091226
1  43bd7feb-3fea-40b4-a140-d01a35ec1f73  2.479458
2  1b04c706-e3d7-4f70-aac8-25635fa24250  1.061739
3  31214d91-d950-4464-8316-ed3d302d49d3  2.074762
4  fbb52038-4db1-46d3-a4de-108fd12cbfc7  2.783758

In [24]:
merged = pd.merge(impressions, clicks, on="id")
merged.tail(50)

,app_id,advertiser_id,country_code,id,revenue
2437,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2438,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2439,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2440,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2441,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2442,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2443,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2444,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2445,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2446,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2447,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2448,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2449,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2450,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2451,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2452,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2453,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2454,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2455,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2456,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2457,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2458,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2459,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2460,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2461,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2462,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2463,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2464,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2465,23,10.0,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
2466,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2467,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2468,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2469,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2470,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2471,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2472,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2473,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2474,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2475,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2476,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2477,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2478,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2479,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2480,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2481,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2482,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2483,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2484,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2485,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030
2486,1,7.0,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030