In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [2]:
impressions_path= "impressions.json"
impressions= pd.read_json(impressions_path)

impressions.drop_duplicates(inplace=True)
nan_value = float("NaN")
impressions.replace("", nan_value, inplace=True)
impressions.dropna(subset = ["country_code"], inplace=True)
impressions = impressions[impressions["country_code" and "id"].str.contains("None" or "NaN")==False]
impressions = impressions.astype({"app_id": int, "advertiser_id": int, "country_code": str, "id": str})
impressions

     app_id  advertiser_id country_code                                    id
0        32              8           UK  a39747e8-9c58-41db-8f9f-27963bc248b5
2         4             15           IT  2ae9fd3f-4c70-4d9f-9fe0-98cb2f0b7521
3        22             20           IT  fbb52038-4db1-46d3-a4de-108fd12cbfc7
7        30             27           DE  8a391b7a-219e-4dc4-af11-8cd98e8165aa
8         9              8           US  f9fe7a5d-5e14-45fa-88e6-438313712694
..      ...            ...          ...                                   ...
412      22             24           DE  917f8813-1ee4-48c0-b3e1-55f1dc108661
423       8             11           DE  5c569d67-59a2-42fa-8a2d-4e0d7fcb6cab
589       1              7           IT  af2c2db3-c854-423e-a940-97b0b90743f2
617      20             30           IT  afc054e3-f1b9-4aea-8f9a-2d084453c4a4
807      29              7           DE  3869394c-ddf6-4286-98a2-85f613754d04

[66 rows x 4 columns]

In [3]:
clicks_path= "clicks.json"
clicks= pd.read_json(clicks_path)

clicks = clicks.rename(columns={"impression_id": "id"})
clicks = clicks.astype({"id": str, "revenue": float})
clicks.tail(50)

                                      id   revenue
45  af2c2db3-c854-423e-a940-97b0b90743f2  2.290030
46  1bf2baef-335d-4a6b-8bdd-dadab491af79  2.730851
47  bf0d23a1-d49c-405d-8288-3246ac184e87  2.613644
48  43bd7feb-3fea-40b4-a140-d01a35ec1f73  0.952998
49  5deacf2d-833a-4549-a398-20a0abeec0bc  1.696280
50  3cd54dd2-6858-4726-8629-e9d672a75591  1.966250
51  b78e16d0-1c4d-4311-838b-363fc7fe28c0  1.529057
52  be2a64b4-7938-4a02-8543-8bdc51b8bf56  2.153987
53  44f6748d-d504-4032-8b52-8668c19a7ac6  0.770963
54  cbbbb827-f702-42fd-9123-bbbb528a9738  1.063414
55  39d90df9-4b89-4ef5-bb70-78713790063e  1.703638
56  be391a1d-b7d6-43af-8beb-a2b393d6b4ce  0.582097
57  687f3be2-2313-4285-8f5e-0ecfad54ffba  2.536704
58  77e8e3b3-de60-4de6-8473-00bf55c45878  1.266355
59  8a391b7a-219e-4dc4-af11-8cd98e8165aa  2.687951
60  b78e16d0-1c4d-4311-838b-363fc7fe28c0  1.025739
61  bdf8f849-1ac2-456e-9b92-a1e5355520f0  1.003607
62  c99f4a5f-6d5b-4bfe-bc4b-26af02f74bb1  1.849348
63  687f3be2-2313-4285-8f5e-0ecfad54ffba  1.076080
64  f30413d6-e526-4adb-a716-721a946bc8d3  0.513334
65  fa30432d-07fd-47e8-92e2-ff2f4ea095d4  1.322516
66  daf69ff1-2057-4ac8-9de0-d2a080cd48a5  2.290023
67  b78e16d0-1c4d-4311-838b-363fc7fe28c0  0.128970
68  e96e4da4-9b15-421b-a2d0-437235945675  0.242942
69  b15449b6-14c9-406b-bce9-749805dd6a3e  2.012665
70  72a5a121-ca88-421e-b2b5-b14d105aeda8  2.135244
71  fdc0a639-4b2d-4332-8f4e-7e08086a78c3  1.853479
72  5b6211e2-cb03-4137-933a-86b36978cb1f  2.345114
73  81cf2616-4fb5-4c47-8517-00dbea47984d  1.671825
74  01e1d53d-a882-4281-86c3-e2ab1a666f18  1.319781
75  3cd54dd2-6858-4726-8629-e9d672a75591  2.402885
76  08ccf808-394a-46d2-b1e7-e941e252d729  1.483241
77  c4587dd9-6eef-4fc5-a701-2e472458b821  0.555919
78  8d5e7dce-bab2-4fcf-bd94-6805f776baf1  0.529268
79  b78e16d0-1c4d-4311-838b-363fc7fe28c0  0.747491
80  980e11e7-92b5-4c64-b00e-1981bafb4e7a  1.588118
81  001a597e-221e-47b3-8928-1c339cd00ea4  1.785073
82  3cd54dd2-6858-4726-8629-e9d672a75591  1.669140
83  b78e16d0-1c4d-4311-838b-363fc7fe28c0  2.441809
84  9d683266-bd60-42dd-9754-e68c100f62ff  1.801546
85  b07af059-4776-4d24-aaea-2c2628c2d613  0.187998
86  5deacf2d-833a-4549-a398-20a0abeec0bc  0.426921
87  daf69ff1-2057-4ac8-9de0-d2a080cd48a5  0.220354
88  fb1af15e-fb01-43c7-bbaf-bcb575ff3832  0.128990
89  77e8e3b3-de60-4de6-8473-00bf55c45878  1.013501
90  2ae9fd3f-4c70-4d9f-9fe0-98cb2f0b7521  2.070345
91  fbb52038-4db1-46d3-a4de-108fd12cbfc7  2.287619
92  a94c843b-97de-4f59-be3c-2f71adeaf961  2.270868
93  11454767-ba1e-4e86-ba00-242dc85e73a4  0.954548
94  b2a60f0d-1d08-4738-9dc5-0eed9cddee82  0.804509

In [4]:
merged = pd.merge(impressions, clicks, on="id")
merged

,app_id,advertiser_id,country_code,id,revenue
0,4,15,IT,2ae9fd3f-4c70-4d9f-9fe0-98cb2f0b7521,2.355039
1,4,15,IT,2ae9fd3f-4c70-4d9f-9fe0-98cb2f0b7521,2.070345
2,22,20,IT,fbb52038-4db1-46d3-a4de-108fd12cbfc7,2.783758
3,22,20,IT,fbb52038-4db1-46d3-a4de-108fd12cbfc7,2.898978
4,22,20,IT,fbb52038-4db1-46d3-a4de-108fd12cbfc7,2.287619
...,...,...,...,...,...
60,33,11,US,fdc0a639-4b2d-4332-8f4e-7e08086a78c3,1.853479
61,21,22,DE,1b04c706-e3d7-4f70-aac8-25635fa24250,1.061739
62,21,22,DE,1b04c706-e3d7-4f70-aac8-25635fa24250,0.110705
63,23,10,US,a94c843b-97de-4f59-be3c-2f71adeaf961,2.270868
64,1,7,IT,af2c2db3-c854-423e-a940-97b0b90743f2,2.290030

In [80]:
impression_count = impressions.groupby(['app_id','country_code'])['id'].size().reset_index(name='impression_count')
impression_count = impression_count.astype({'impression_count': int})
impression_count

    app_id country_code  impression_count
0        0           IT                 1
1        1           IT                 1
2        4           IT                 1
3        4           UK                 1
4        5           DE                 1
5        5           IT                 1
6        5           US                 2
7        6           DE                 1
8        6           US                 2
9        7           DE                 1
10       7           IT                 2
11       8           DE                 1
12       9           IT                 1
13       9           US                 1
14      10           DE                 2
15      10           US                 1
16      11           US                 1
17      12           IT                 1
18      13           DE                 1
19      13           US                 1
20      14           UK                 1
21      14           US                 1
22      15           US                 1
23      16           UK                 1
24      16           US                 1
25      18           DE                 1
26      18           IT                 1
27      19           DE                 1
28      19           UK                 1
29      19           US                 1
30      20           IT                 1
31      21           DE                 1
32      21           IT                 1
33      22           DE                 2
34      22           IT                 1
35      23           US                 2
36      24           UK                 1
37      25           UK                 1
38      26           DE                 1
39      26           US                 1
40      27           IT                 1
41      28           US                 1
42      29           DE                 1
43      30           DE                 1
44      30           US                 2
45      32           DE                 1
46      32           UK                 1
47      33           US                 1
48      34           DE                 1
49      34           IT                 1
50      35           IT                 1
51      35           US                 1
52      38           IT                 2
53      39           US                 1
54      40           DE                 2
55      40           US                 2

In [82]:
click_count = merged.groupby(['app_id','country_code'])['revenue'].size().reset_index(name='click_count')
click_count

    app_id country_code  click_count
0        1           IT            1
1        4           IT            2
2        5           DE            1
3        5           IT            2
4        7           DE            1
5        7           IT            1
6        9           US            2
7       10           US            2
8       11           US            1
9       13           DE            1
10      13           US            2
11      14           UK            1
12      15           US            1
13      16           UK            4
14      16           US            3
15      18           DE            1
16      18           IT            1
17      21           DE            2
18      22           DE            2
19      22           IT            3
20      23           US            3
21      24           UK            2
22      25           UK            1
23      26           DE            1
24      27           IT            1
25      28           US            4
26      30           DE            2
27      30           US            6
28      33           US            1
29      34           DE            2
30      35           IT            1
31      38           IT            2
32      39           US            1
33      40           DE            4

In [83]:
revenue = merged.groupby(['app_id','country_code'])['revenue'].sum().reset_index()
revenue

    app_id country_code   revenue
0        1           IT  2.290030
1        4           IT  4.425384
2        5           DE  0.788711
3        5           IT  5.136534
4        7           DE  0.356624
5        7           IT  0.934817
6        9           US  2.789852
7       10           US  1.348501
8       11           US  1.785073
9       13           DE  0.463224
10      13           US  2.605671
11      14           UK  2.345114
12      15           US  2.135244
13      16           UK  7.016603
14      16           US  4.983315
15      18           DE  0.388200
16      18           IT  2.880423
17      21           DE  1.172445
18      22           DE  4.960972
19      22           IT  7.970356
20      23           US  4.550725
21      24           UK  3.432455
22      25           UK  1.849348
23      26           DE  1.588118
24      27           IT  0.582097
25      28           US  8.327080
26      30           DE  4.589644
27      30           US  5.911654
28      33           US  1.853479
29      34           DE  3.698559
30      35           IT  0.242942
31      38           IT  2.596509
32      39           US  1.319781
33      40           DE  5.879892

In [85]:
metric=pd.merge(click_count, revenue)
metric

    app_id country_code  click_count   revenue
0        1           IT            1  2.290030
1        4           IT            2  4.425384
2        5           DE            1  0.788711
3        5           IT            2  5.136534
4        7           DE            1  0.356624
5        7           IT            1  0.934817
6        9           US            2  2.789852
7       10           US            2  1.348501
8       11           US            1  1.785073
9       13           DE            1  0.463224
10      13           US            2  2.605671
11      14           UK            1  2.345114
12      15           US            1  2.135244
13      16           UK            4  7.016603
14      16           US            3  4.983315
15      18           DE            1  0.388200
16      18           IT            1  2.880423
17      21           DE            2  1.172445
18      22           DE            2  4.960972
19      22           IT            3  7.970356
20      23           US            3  4.550725
21      24           UK            2  3.432455
22      25           UK            1  1.849348
23      26           DE            1  1.588118
24      27           IT            1  0.582097
25      28           US            4  8.327080
26      30           DE            2  4.589644
27      30           US            6  5.911654
28      33           US            1  1.853479
29      34           DE            2  3.698559
30      35           IT            1  0.242942
31      38           IT            2  2.596509
32      39           US            1  1.319781
33      40           DE            4  5.879892

In [89]:
metrics=pd.merge(impression_count, metric, how='left').fillna(0)
metrics

    app_id country_code  impression_count  click_count   revenue
0        0           IT                 1          0.0  0.000000
1        1           IT                 1          1.0  2.290030
2        4           IT                 1          2.0  4.425384
3        4           UK                 1          0.0  0.000000
4        5           DE                 1          1.0  0.788711
5        5           IT                 1          2.0  5.136534
6        5           US                 2          0.0  0.000000
7        6           DE                 1          0.0  0.000000
8        6           US                 2          0.0  0.000000
9        7           DE                 1          1.0  0.356624
10       7           IT                 2          1.0  0.934817
11       8           DE                 1          0.0  0.000000
12       9           IT                 1          0.0  0.000000
13       9           US                 1          2.0  2.789852
14      10           DE                 2          0.0  0.000000
15      10           US                 1          2.0  1.348501
16      11           US                 1          1.0  1.785073
17      12           IT                 1          0.0  0.000000
18      13           DE                 1          1.0  0.463224
19      13           US                 1          2.0  2.605671
20      14           UK                 1          1.0  2.345114
21      14           US                 1          0.0  0.000000
22      15           US                 1          1.0  2.135244
23      16           UK                 1          4.0  7.016603
24      16           US                 1          3.0  4.983315
25      18           DE                 1          1.0  0.388200
26      18           IT                 1          1.0  2.880423
27      19           DE                 1          0.0  0.000000
28      19           UK                 1          0.0  0.000000
29      19           US                 1          0.0  0.000000
30      20           IT                 1          0.0  0.000000
31      21           DE                 1          2.0  1.172445
32      21           IT                 1          0.0  0.000000
33      22           DE                 2          2.0  4.960972
34      22           IT                 1          3.0  7.970356
35      23           US                 2          3.0  4.550725
36      24           UK                 1          2.0  3.432455
37      25           UK                 1          1.0  1.849348
38      26           DE                 1          1.0  1.588118
39      26           US                 1          0.0  0.000000
40      27           IT                 1          1.0  0.582097
41      28           US                 1          4.0  8.327080
42      29           DE                 1          0.0  0.000000
43      30           DE                 1          2.0  4.589644
44      30           US                 2          6.0  5.911654
45      32           DE                 1          0.0  0.000000
46      32           UK                 1          0.0  0.000000
47      33           US                 1          1.0  1.853479
48      34           DE                 1          2.0  3.698559
49      34           IT                 1          0.0  0.000000
50      35           IT                 1          1.0  0.242942
51      35           US                 1          0.0  0.000000
52      38           IT                 2          2.0  2.596509
53      39           US                 1          1.0  1.319781
54      40           DE                 2          4.0  5.879892
55      40           US                 2          0.0  0.000000

In [90]:
metrics= metrics.rename(columns={"impression_count": "impressions", "click_count": "clicks"})
metrics= metrics[['app_id', 'country_code', 'impressions', 'clicks', 'revenue']]

In [91]:
metrics["rate_per_click"] = metrics["revenue"]/metrics["impressions"]
metrics

    app_id country_code  impressions  clicks   revenue  rate_per_click
0        0           IT            1     0.0  0.000000        0.000000
1        1           IT            1     1.0  2.290030        2.290030
2        4           IT            1     2.0  4.425384        4.425384
3        4           UK            1     0.0  0.000000        0.000000
4        5           DE            1     1.0  0.788711        0.788711
5        5           IT            1     2.0  5.136534        5.136534
6        5           US            2     0.0  0.000000        0.000000
7        6           DE            1     0.0  0.000000        0.000000
8        6           US            2     0.0  0.000000        0.000000
9        7           DE            1     1.0  0.356624        0.356624
10       7           IT            2     1.0  0.934817        0.467408
11       8           DE            1     0.0  0.000000        0.000000
12       9           IT            1     0.0  0.000000        0.000000
13       9           US            1     2.0  2.789852        2.789852
14      10           DE            2     0.0  0.000000        0.000000
15      10           US            1     2.0  1.348501        1.348501
16      11           US            1     1.0  1.785073        1.785073
17      12           IT            1     0.0  0.000000        0.000000
18      13           DE            1     1.0  0.463224        0.463224
19      13           US            1     2.0  2.605671        2.605671
20      14           UK            1     1.0  2.345114        2.345114
21      14           US            1     0.0  0.000000        0.000000
22      15           US            1     1.0  2.135244        2.135244
23      16           UK            1     4.0  7.016603        7.016603
24      16           US            1     3.0  4.983315        4.983315
25      18           DE            1     1.0  0.388200        0.388200
26      18           IT            1     1.0  2.880423        2.880423
27      19           DE            1     0.0  0.000000        0.000000
28      19           UK            1     0.0  0.000000        0.000000
29      19           US            1     0.0  0.000000        0.000000
30      20           IT            1     0.0  0.000000        0.000000
31      21           DE            1     2.0  1.172445        1.172445
32      21           IT            1     0.0  0.000000        0.000000
33      22           DE            2     2.0  4.960972        2.480486
34      22           IT            1     3.0  7.970356        7.970356
35      23           US            2     3.0  4.550725        2.275362
36      24           UK            1     2.0  3.432455        3.432455
37      25           UK            1     1.0  1.849348        1.849348
38      26           DE            1     1.0  1.588118        1.588118
39      26           US            1     0.0  0.000000        0.000000
40      27           IT            1     1.0  0.582097        0.582097
41      28           US            1     4.0  8.327080        8.327080
42      29           DE            1     0.0  0.000000        0.000000
43      30           DE            1     2.0  4.589644        4.589644
44      30           US            2     6.0  5.911654        2.955827
45      32           DE            1     0.0  0.000000        0.000000
46      32           UK            1     0.0  0.000000        0.000000
47      33           US            1     1.0  1.853479        1.853479
48      34           DE            1     2.0  3.698559        3.698559
49      34           IT            1     0.0  0.000000        0.000000
50      35           IT            1     1.0  0.242942        0.242942
51      35           US            1     0.0  0.000000        0.000000
52      38           IT            2     2.0  2.596509        1.298255
53      39           US            1     1.0  1.319781        1.319781
54      40           DE            2     4.0  5.879892        2.939946
55      40           US            2     0.0  0.000000        0.000000

In [97]:
top5=pd.merge(metrics, impressions, how='left').fillna('NA')
top5.head(50)


#top5=metrics['advertiser_id'].groupby([metrics.app_id, metrics.country_code]).apply(list).reset_index()
#top5=top5.rename(columns={"advertiser_id": "recommended_advertiser_ids"})
#top5

,app_id,country_code,impressions,clicks,revenue,rate_per_click,advertiser_id,id
0,0,IT,1,0.0,0.000000,0.000000,22,591941fc-4a12-46c8-81ae-b33b3cf8ce32
1,1,IT,1,1.0,2.290030,2.290030,7,af2c2db3-c854-423e-a940-97b0b90743f2
2,4,IT,1,2.0,4.425384,4.425384,15,2ae9fd3f-4c70-4d9f-9fe0-98cb2f0b7521
3,4,UK,1,0.0,0.000000,0.000000,32,a7827ab6-c4d2-475f-ab56-3a19c3172184
4,5,DE,1,1.0,0.788711,0.788711,21,e3e7169e-2014-4001-8b55-1eda0cbb21bc
5,5,IT,1,2.0,5.136534,5.136534,12,ab769c09-d2e8-499b-8e8f-017c526910c8
6,5,US,2,0.0,0.000000,0.000000,25,23eb72a5-6f0a-4767-988c-dd3f14c622a1
7,5,US,2,0.0,0.000000,0.000000,10,18305dd6-46e1-40f4-aa04-c88ea3e6be98
8,6,DE,1,0.0,0.000000,0.000000,15,9e00bde2-8d14-4678-94c3-e7b5fef53d8c
9,6,US,2,0.0,0.000000,0.000000,31,204c38ac-802e-4558-ac5d-24a0b004a1f9
10,6,US,2,0.0,0.000000,0.000000,16,3eff0d78-6517-4a88-b090-bc4b372c5cc3
11,7,DE,1,1.0,0.356624,0.356624,20,0c667f97-86cc-4393-bd4b-c41ce231fbb8
12,7,IT,2,1.0,0.934817,0.467408,6,765c0ae9-4765-41a5-bd06-32783c92dbbf
13,7,IT,2,1.0,0.934817,0.467408,6,a36d3dfa-ed73-4977-8109-8fcf322d5495
14,8,DE,1,0.0,0.000000,0.000000,11,5c569d67-59a2-42fa-8a2d-4e0d7fcb6cab
15,9,IT,1,0.0,0.000000,0.000000,29,2e8b7e2e-37d6-4d7e-a9ef-17efe8bff065
16,9,US,1,2.0,2.789852,2.789852,8,f9fe7a5d-5e14-45fa-88e6-438313712694
17,10,DE,2,0.0,0.000000,0.000000,14,b0a456d2-5d01-40b3-9b67-67ce96789c77
18,10,DE,2,0.0,0.000000,0.000000,16,5f47f89d-49e2-41c6-8982-01928b5dba05
19,10,US,1,2.0,1.348501,1.348501,22,8d5e7dce-bab2-4fcf-bd94-6805f776baf1
20,11,US,1,1.0,1.785073,1.785073,18,001a597e-221e-47b3-8928-1c339cd00ea4
21,12,IT,1,0.0,0.000000,0.000000,19,124c2202-559c-4215-af94-787401598b5d
22,13,DE,1,1.0,0.463224,0.463224,10,1bf00ce9-e999-4029-813e-66d1ddc6b209
23,13,US,1,2.0,2.605671,2.605671,12,bdf8f849-1ac2-456e-9b92-a1e5355520f0
24,14,UK,1,1.0,2.345114,2.345114,10,5b6211e2-cb03-4137-933a-86b36978cb1f
25,14,US,1,0.0,0.000000,0.000000,9,4a7ed0cb-e954-4aba-9e94-b181d593eee4
26,15,US,1,1.0,2.135244,2.135244,34,72a5a121-ca88-421e-b2b5-b14d105aeda8
27,16,UK,1,4.0,7.016603,7.016603,17,687f3be2-2313-4285-8f5e-0ecfad54ffba
28,16,US,1,3.0,4.983315,4.983315,7,97dd2a0f-6d42-4c63-8cd6-5270c19f20d6
29,18,DE,1,1.0,0.388200,0.388200,10,6e25e2a5-8759-40c0-9f82-b52c0d1e27c7
30,18,IT,1,1.0,2.880423,2.880423,16,d73d8029-ce13-43c3-99b1-1676beeb9dd7
31,19,DE,1,0.0,0.000000,0.000000,11,20bb8b6c-ec0b-41f2-8c13-781bf2a2d22d
32,19,UK,1,0.0,0.000000,0.000000,16,5a0be656-b4a1-41ea-b902-47a5512e704f
33,19,US,1,0.0,0.000000,0.000000,22,049c7e7b-b4b1-499d-97ed-4c3e361a593a
34,20,IT,1,0.0,0.000000,0.000000,30,afc054e3-f1b9-4aea-8f9a-2d084453c4a4
35,21,DE,1,2.0,1.172445,1.172445,22,1b04c706-e3d7-4f70-aac8-25635fa24250
36,21,IT,1,0.0,0.000000,0.000000,10,84365cb7-14d9-44de-a36e-ca5acc94af36
37,22,DE,2,2.0,4.960972,2.480486,20,31214d91-d950-4464-8316-ed3d302d49d3
38,22,DE,2,2.0,4.960972,2.480486,24,917f8813-1ee4-48c0-b3e1-55f1dc108661
39,22,IT,1,3.0,7.970356,7.970356,20,fbb52038-4db1-46d3-a4de-108fd12cbfc7
40,23,US,2,3.0,4.550725,2.275362,17,77e8e3b3-de60-4de6-8473-00bf55c45878
41,23,US,2,3.0,4.550725,2.275362,10,a94c843b-97de-4f59-be3c-2f71adeaf961
42,24,UK,1,2.0,3.432455,3.432455,19,43bd7feb-3fea-40b4-a140-d01a35ec1f73
43,25,UK,1,1.0,1.849348,1.849348,11,c99f4a5f-6d5b-4bfe-bc4b-26af02f74bb1
44,26,DE,1,1.0,1.588118,1.588118,16,980e11e7-92b5-4c64-b00e-1981bafb4e7a
45,26,US,1,0.0,0.000000,0.000000,17,74a7cd15-f2b4-48b3-a5f0-ed966978746f
46,27,IT,1,1.0,0.582097,0.582097,14,be391a1d-b7d6-43af-8beb-a2b393d6b4ce
47,28,US,1,4.0,8.327080,8.327080,29,3cd54dd2-6858-4726-8629-e9d672a75591
48,29,DE,1,0.0,0.000000,0.000000,7,3869394c-ddf6-4286-98a2-85f613754d04
49,30,DE,1,2.0,4.589644,4.589644,27,8a391b7a-219e-4dc4-af11-8cd98e8165aa

In [98]:
recommended_advertisers=top5['advertiser_id'].groupby([top5.app_id, top5.country_code]).apply(list).reset_index()
recommended_advertisers=recommended_advertisers.rename(columns={"advertiser_id": "recommended_advertiser_ids"})
recommended_advertisers

    app_id country_code recommended_advertiser_ids
0        0           IT                       [22]
1        1           IT                        [7]
2        4           IT                       [15]
3        4           UK                       [32]
4        5           DE                       [21]
5        5           IT                       [12]
6        5           US                   [25, 10]
7        6           DE                       [15]
8        6           US                   [31, 16]
9        7           DE                       [20]
10       7           IT                     [6, 6]
11       8           DE                       [11]
12       9           IT                       [29]
13       9           US                        [8]
14      10           DE                   [14, 16]
15      10           US                       [22]
16      11           US                       [18]
17      12           IT                       [19]
18      13           DE                       [10]
19      13           US                       [12]
20      14           UK                       [10]
21      14           US                        [9]
22      15           US                       [34]
23      16           UK                       [17]
24      16           US                        [7]
25      18           DE                       [10]
26      18           IT                       [16]
27      19           DE                       [11]
28      19           UK                       [16]
29      19           US                       [22]
30      20           IT                       [30]
31      21           DE                       [22]
32      21           IT                       [10]
33      22           DE                   [20, 24]
34      22           IT                       [20]
35      23           US                   [17, 10]
36      24           UK                       [19]
37      25           UK                       [11]
38      26           DE                       [16]
39      26           US                       [17]
40      27           IT                       [14]
41      28           US                       [29]
42      29           DE                        [7]
43      30           DE                       [27]
44      30           US                    [9, 28]
45      32           DE                       [10]
46      32           UK                        [8]
47      33           US                       [11]
48      34           DE                       [28]
49      34           IT                       [17]
50      35           IT                       [33]
51      35           US                       [33]
52      38           IT                   [28, 10]
53      39           US                        [5]
54      40           DE                   [14, 30]
55      40           US                   [31, 26]

In [99]:
recommended_advertisers.to_json('recommended_advertiser_ids.json', orient='records')

In [100]:
metrics= metrics[['app_id', 'country_code', 'impressions', 'clicks', 'revenue']]
metrics

    app_id country_code  impressions  clicks   revenue
0        0           IT            1     0.0  0.000000
1        1           IT            1     1.0  2.290030
2        4           IT            1     2.0  4.425384
3        4           UK            1     0.0  0.000000
4        5           DE            1     1.0  0.788711
5        5           IT            1     2.0  5.136534
6        5           US            2     0.0  0.000000
7        6           DE            1     0.0  0.000000
8        6           US            2     0.0  0.000000
9        7           DE            1     1.0  0.356624
10       7           IT            2     1.0  0.934817
11       8           DE            1     0.0  0.000000
12       9           IT            1     0.0  0.000000
13       9           US            1     2.0  2.789852
14      10           DE            2     0.0  0.000000
15      10           US            1     2.0  1.348501
16      11           US            1     1.0  1.785073
17      12           IT            1     0.0  0.000000
18      13           DE            1     1.0  0.463224
19      13           US            1     2.0  2.605671
20      14           UK            1     1.0  2.345114
21      14           US            1     0.0  0.000000
22      15           US            1     1.0  2.135244
23      16           UK            1     4.0  7.016603
24      16           US            1     3.0  4.983315
25      18           DE            1     1.0  0.388200
26      18           IT            1     1.0  2.880423
27      19           DE            1     0.0  0.000000
28      19           UK            1     0.0  0.000000
29      19           US            1     0.0  0.000000
30      20           IT            1     0.0  0.000000
31      21           DE            1     2.0  1.172445
32      21           IT            1     0.0  0.000000
33      22           DE            2     2.0  4.960972
34      22           IT            1     3.0  7.970356
35      23           US            2     3.0  4.550725
36      24           UK            1     2.0  3.432455
37      25           UK            1     1.0  1.849348
38      26           DE            1     1.0  1.588118
39      26           US            1     0.0  0.000000
40      27           IT            1     1.0  0.582097
41      28           US            1     4.0  8.327080
42      29           DE            1     0.0  0.000000
43      30           DE            1     2.0  4.589644
44      30           US            2     6.0  5.911654
45      32           DE            1     0.0  0.000000
46      32           UK            1     0.0  0.000000
47      33           US            1     1.0  1.853479
48      34           DE            1     2.0  3.698559
49      34           IT            1     0.0  0.000000
50      35           IT            1     1.0  0.242942
51      35           US            1     0.0  0.000000
52      38           IT            2     2.0  2.596509
53      39           US            1     1.0  1.319781
54      40           DE            2     4.0  5.879892
55      40           US            2     0.0  0.000000

In [101]:
metrics.to_json('metrics.json', orient='records')